import styles from './SlidePreview.module.css'

export default function SlidePreview({ data }) {
  return (
    <div className={styles.slide}>
      <div className={styles.slideHeader}>
        <div>
          <h2 className={styles.company}>{data.company}</h2>
          {data.ticker && (
            <span className={styles.ticker}>{data.ticker}</span>
          )}
        </div>
        <span className={styles.badge}>Research Brief</span>
      </div>

      {data.overview && (
        <p className={styles.overview}>{data.overview}</p>
      )}

      <div className={styles.grid}>
        {data.keyMetrics && data.keyMetrics.length > 0 && (
          <div className={styles.section}>
            <h3 className={styles.sectionTitle}>Key Metrics</h3>
            <ul className={styles.list}>
              {data.keyMetrics.map((item, i) => (
                <li key={i} className={styles.listItem}>
                  {item}
                </li>
              ))}
            </ul>
          </div>
        )}

        {data.strategicPriorities && data.strategicPriorities.length > 0 && (
          <div className={styles.section}>
            <h3 className={styles.sectionTitle}>Strategic Priorities</h3>
            <ul className={styles.list}>
              {data.strategicPriorities.map((item, i) => (
                <li key={i} className={styles.listItem}>
                  {item}
                </li>
              ))}
            </ul>
          </div>
        )}

        {data.opportunities && data.opportunities.length > 0 && (
          <div className={styles.section}>
            <h3 className={styles.sectionTitle}>Opportunities</h3>
            <ul className={styles.list}>
              {data.opportunities.map((item, i) => (
                <li key={i} className={styles.listItem}>
                  {item}
                </li>
              ))}
            </ul>
          </div>
        )}

        {data.risks && data.risks.length > 0 && (
          <div className={styles.section}>
            <h3 className={styles.sectionTitle}>Key Risks</h3>
            <ul className={styles.list}>
              {data.risks.map((item, i) => (
                <li key={i} className={styles.listItem}>
                  {item}
                </li>
              ))}
            </ul>
          </div>
        )}
      </div>

      <div className={styles.slideFooter}>
        <span>Source: Annual reports, 10-K filings, investor relations</span>
        <span>Generated by Account Research Intelligence</span>
      </div>
    </div>
  )
}
