import PptxGenJS from 'pptxgenjs'

const COLORS = {
  dark: '1A1A2E',
  accent: 'E94560',
  white: 'FFFFFF',
  gray: '666666',
  lightGray: 'EEEEEE',
}

export async function generatePptx(data) {
  const pptx = new PptxGenJS()
  pptx.layout = 'LAYOUT_16x9'
  pptx.author = 'Account Research Intelligence'
  pptx.title = `${data.company} — Research Brief`

  const slide = pptx.addSlide()
  slide.background = { color: COLORS.white }

  slide.addShape(pptx.ShapeType.rect, {
    x: 0,
    y: 0,
    w: '100%',
    h: 0.06,
    fill: { color: COLORS.accent },
  })

  slide.addText(data.company, {
    x: 0.5,
    y: 0.25,
    w: 7,
    h: 0.5,
    fontSize: 24,
    fontFace: 'Arial',
    bold: true,
    color: COLORS.dark,
  })

  if (data.ticker) {
    slide.addText(data.ticker, {
      x: 0.5,
      y: 0.7,
      w: 2,
      h: 0.3,
      fontSize: 12,
      fontFace: 'Arial',
      bold: true,
      color: COLORS.accent,
    })
  }

  slide.addShape(pptx.ShapeType.rect, {
    x: 0.5,
    y: 1.0,
    w: 9,
    h: 0.02,
    fill: { color: COLORS.accent },
  })

  if (data.overview) {
    slide.addText(data.overview, {
      x: 0.5,
      y: 1.15,
      w: 9,
      h: 0.6,
      fontSize: 10,
      fontFace: 'Arial',
      color: COLORS.gray,
      valign: 'top',
      wrap: true,
    })
  }

  const sections = [
    { title: 'Key Metrics', items: data.keyMetrics },
    { title: 'Strategic Priorities', items: data.strategicPriorities },
    { title: 'Opportunities', items: data.opportunities },
    { title: 'Key Risks', items: data.risks },
  ].filter((s) => s.items && s.items.length > 0)

  const colWidth = 4.35
  const startY = 1.85

  sections.forEach((section, idx) => {
    const col = idx % 2
    const row = Math.floor(idx / 2)
    const x = 0.5 + col * (colWidth + 0.3)
    const y = startY + row * 1.7

    slide.addText(section.title.toUpperCase(), {
      x,
      y,
      w: colWidth,
      h: 0.25,
      fontSize: 9,
      fontFace: 'Arial',
      bold: true,
      color: COLORS.accent,
    })

    const bullets = section.items.map((item) => ({
      text: item,
      options: { bullet: { code: '2022' }, indentLevel: 0 },
    }))

    slide.addText(bullets, {
      x,
      y: y + 0.3,
      w: colWidth,
      h: 1.3,
      fontSize: 9,
      fontFace: 'Arial',
      color: COLORS.dark,
      valign: 'top',
      lineSpacingMultiple: 1.2,
      wrap: true,
    })
  })

  slide.addText(
    'Source: Annual reports, 10-K filings, investor relations materials',
    {
      x: 0.5,
      y: 5.05,
      w: 6,
      h: 0.25,
      fontSize: 7,
      fontFace: 'Arial',
      color: COLORS.gray,
    }
  )

  slide.addText('Generated by Account Research Intelligence', {
    x: 6.5,
    y: 5.05,
    w: 3,
    h: 0.25,
    fontSize: 7,
    fontFace: 'Arial',
    color: COLORS.gray,
    align: 'right',
  })

  const fileName = `${data.company.replace(/[^a-zA-Z0-9]/g, '_')}_Research_Brief.pptx`
  await pptx.writeFile({ fileName })
}
